### ISSUE TITLE
Changelog does not link to issues and authors

### ISSUE THREAD

**Issue by clue** [reactphp/website#22]
The changelog for each component does not currently link to issues (`#NUMBER`) or author names (`@NAME`). Compare for example https://reactphp.org/stream/changelog.html with https://github.com/reactphp/stream/releases.

I think it makes sense to implement this feature so that links are added automatically for consistency reasons. This only applies to the changelog and not the other markdown files, so I suppose it's relatively safe to apply some simple regular expressions here.

Any input is welcome :+1:

**Comment by jsor** [comment]
That's just because we're rendering the changelog like all other markdown files, so the comparision should be https://reactphp.org/stream/changelog.html with https://github.com/reactphp/stream/blob/master/CHANGELOG.md.

Another option would be to read the releases from the [GH api](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository), parse the body in [`gfm`](https://developer.github.com/v3/markdown/#render-an-arbitrary-markdown-document) mode and build the list ourself.

**Comment by clue** [comment]
@jsor I understand why this is currently not linked and agree that comparing this to the raw CHANGELOG.md does indeed make sense.

As an alternative, we *could* also ensure that each of our CHANGELOG.md files contains full links instead of relying on auto-linking. I recall doing this for some of my projects a while back, but figured it's not really worth the effort as it does cause some overhead for each and every release. What do you suggest?
